### ISSUE TITLE
To be prozess

### ISSUE THREAD

**Issue by martin-fhnw** [DigiBP/DigiBP_Burrata#11]
-Auf High Level Ebene
-Vorteile von automatisiertem/digitalisierten Prozess für Arzt und Patient
-Nicht auf einezelne Schritte eingehen
-Was sind die Vorteile, die wir uns versprechen?
-Was triggert den Prozess? Wie nimmt der Patient Kontakt mit dem Bot auf? Generisch bleiben.
-User Experience: auf was setzen wir? Mobiltelefon, interaktiv, etc. oberflächlich bleiben

Identify and clarify digitalization aspects and entry points.

**Comment by Axeirus** [comment]
done. bitte reviewen.
